import { DoctorOption, FacilityOption, Appointment } from '../types/appointment';
import { FollowUp } from '../types/followup';

export const DEMO_FACILITIES: FacilityOption[] = [
  {
    id: 'FAC-PHC-SHIRPUR',
    name: 'Primary Health Centre (Shirpur PHC)',
    type: 'Primary Health Centre',
    location: 'Shirpur, Dhule',
  },
  {
    id: 'FAC-RH-SAKRI',
    name: 'Rural Hospital (Sakri RH)',
    type: 'Rural Hospital',
    location: 'Sakri, Dhule',
  },
  {
    id: 'FAC-DH-DHULE',
    name: 'District Hospital (Dhule Civil)',
    type: 'District Hospital',
    location: 'Dhule City',
  },
];

export const DEMO_DOCTORS: DoctorOption[] = [
  {
    id: 'DOC-ANJALI-01',
    name: 'Dr. Anjali Sharma',
    specialty: 'General Physician & Family Medicine',
    facilityId: 'FAC-PHC-SHIRPUR',
    facilityName: 'Primary Health Centre (Shirpur PHC)',
    availability: 'Mon - Sat (09:00 AM - 01:00 PM, 02:00 PM - 05:00 PM)',
  },
  {
    id: 'DOC-RAJESH-02',
    name: 'Dr. Rajesh Varma',
    specialty: 'Pediatrician (Child Specialist)',
    facilityId: 'FAC-RH-SAKRI',
    facilityName: 'Rural Hospital (Sakri RH)',
    availability: 'Mon - Fri (10:00 AM - 02:00 PM)',
  },
  {
    id: 'DOC-MAHAJAN-03',
    name: 'Dr. S. K. Mahajan',
    specialty: 'Chest Physician / Pulmonologist',
    facilityId: 'FAC-DH-DHULE',
    facilityName: 'District Hospital (Dhule Civil)',
    availability: 'Tue, Thu, Sat (11:00 AM - 04:00 PM)',
  },
  {
    id: 'DOC-PRIYA-04',
    name: 'Dr. Priya Patil',
    specialty: 'Obstetrician & Gynecologist (OB/GYN)',
    facilityId: 'FAC-PHC-SHIRPUR',
    facilityName: 'Primary Health Centre (Shirpur PHC)',
    availability: 'Mon - Sat (09:30 AM - 01:30 PM)',
  },
];

export const AVAILABLE_TIME_SLOTS = [
  '09:30 AM',
  '10:00 AM',
  '10:30 AM',
  '11:00 AM',
  '11:30 AM',
  '12:00 PM',
  '02:00 PM',
  '02:30 PM',
  '03:00 PM',
  '03:30 PM',
  '04:00 PM',
];

// Helper: Today's date in IST
export const getTodayIST = (): string => {
  const now = new Date();
  const istOffset = 5.5 * 60 * 60 * 1000;
  const istDate = new Date(now.getTime() + istOffset);
  return istDate.toISOString().split('T')[0];
};

// Generate baseline demo appointments for today and upcoming
export const getBaselineAppointments = (): Appointment[] => {
  const today = getTodayIST();
  return [
    {
      appointmentId: 'APT-2026-00121',
      patientId: 'RC-2026-004821',
      patientName: 'Suresh Patil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      triageId: 'TRIAGE-2026-0001',
      date: today,
      time: '10:00 AM',
      mode: 'IN_PERSON',
      reason: 'Acute shortness of breath & productive cough triage review',
      tokenNumber: 'P-021',
      status: 'WAITING',
      createdAt: `${today}T09:15:00.000Z`,
      updatedAt: `${today}T09:40:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00122',
      patientId: 'RC-2026-001042',
      patientName: 'Aarav Bhil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '10:30 AM',
      mode: 'IN_PERSON',
      reason: 'Persistent fever and dehydration evaluation',
      tokenNumber: 'P-022',
      status: 'WAITING',
      createdAt: `${today}T09:20:00.000Z`,
      updatedAt: `${today}T10:05:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00123',
      patientId: 'RC-2026-003290',
      patientName: 'Kavita Gawit',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-PRIYA-04',
      doctorName: 'Dr. Priya Patil',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '11:00 AM',
      mode: 'TELECONSULTATION',
      reason: 'Antenatal second trimester checkup & iron supplements',
      tokenNumber: 'P-023',
      status: 'WAITING',
      createdAt: `${today}T09:30:00.000Z`,
      updatedAt: `${today}T10:15:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00124',
      patientId: 'RC-2026-002115',
      patientName: 'Namdeo Sonawane',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '11:30 AM',
      mode: 'HW_ASSISTED',
      reason: 'Chronic osteoarthritis knee joint pain management',
      tokenNumber: 'P-024',
      status: 'WAITING',
      createdAt: `${today}T09:45:00.000Z`,
      updatedAt: `${today}T10:30:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00115',
      patientId: 'RC-2026-005102',
      patientName: 'Shantabai Bhil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '09:30 AM',
      mode: 'IN_PERSON',
      reason: 'Severe migraine headache consultation',
      tokenNumber: 'P-015',
      status: 'COMPLETED',
      createdAt: `${today}T08:30:00.000Z`,
      updatedAt: `${today}T10:00:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00116',
      patientId: 'RC-2026-005118',
      patientName: 'Kishor Wagh',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '09:00 AM',
      mode: 'IN_PERSON',
      reason: 'Skin rash & allergic dermatitis check',
      tokenNumber: 'P-014',
      status: 'COMPLETED',
      createdAt: `${today}T08:15:00.000Z`,
      updatedAt: `${today}T09:25:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00117',
      patientId: 'RC-2026-005129',
      patientName: 'Devidas More',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '08:30 AM',
      mode: 'IN_PERSON',
      reason: 'Fasting blood glucose routine check',
      tokenNumber: 'P-012',
      status: 'COMPLETED',
      createdAt: `${today}T08:00:00.000Z`,
      updatedAt: `${today}T08:55:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00118',
      patientId: 'RC-2026-005135',
      patientName: 'Rekha Padvi',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-PRIYA-04',
      doctorName: 'Dr. Priya Patil',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '08:45 AM',
      mode: 'IN_PERSON',
      reason: 'Postpartum wound inspection',
      tokenNumber: 'P-013',
      status: 'COMPLETED',
      createdAt: `${today}T08:10:00.000Z`,
      updatedAt: `${today}T09:10:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00119',
      patientId: 'RC-2026-005141',
      patientName: 'Anil Jadhav',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-RAJESH-02',
      doctorName: 'Dr. Rajesh Varma',
      facilityId: 'FAC-RH-SAKRI',
      facilityName: 'Rural Hospital Sakri (Sub-District RH)',
      date: today,
      time: '09:15 AM',
      mode: 'TELECONSULTATION',
      reason: 'Child ear infection assessment',
      tokenNumber: 'P-016',
      status: 'COMPLETED',
      createdAt: `${today}T08:40:00.000Z`,
      updatedAt: `${today}T09:40:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00120',
      patientId: 'RC-2026-005150',
      patientName: 'Sunita Chaudhari',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '09:45 AM',
      mode: 'IN_PERSON',
      reason: 'Hypertension prescription review',
      tokenNumber: 'P-017',
      status: 'COMPLETED',
      createdAt: `${today}T08:50:00.000Z`,
      updatedAt: `${today}T10:10:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00110',
      patientId: 'RC-2026-005162',
      patientName: 'Bhaskar Gavit',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '12:00 PM',
      mode: 'IN_PERSON',
      reason: 'Patient relocated to Dhule for family emergency',
      tokenNumber: 'P-018',
      status: 'CANCELLED',
      cancelReason: 'Patient called to cancel due to emergency family travel',
      createdAt: `${today}T08:00:00.000Z`,
      updatedAt: `${today}T09:00:00.000Z`,
      syncStatus: 'synced',
    },
    {
      appointmentId: 'APT-2026-00111',
      patientId: 'RC-2026-005175',
      patientName: 'Rukminibai Shinde',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-PRIYA-04',
      doctorName: 'Dr. Priya Patil',
      facilityId: 'FAC-PHC-SHIRPUR',
      facilityName: 'Primary Health Centre (Shirpur PHC)',
      date: today,
      time: '02:00 PM',
      mode: 'IN_PERSON',
      reason: 'Patient already examined at village sub-center camp',
      tokenNumber: 'P-019',
      status: 'CANCELLED',
      cancelReason: 'Condition already reviewed during morning village field camp',
      createdAt: `${today}T08:10:00.000Z`,
      updatedAt: `${today}T09:30:00.000Z`,
      syncStatus: 'synced',
    },
  ];
};

// Generate baseline demo follow-ups
export const getBaselineFollowUps = (): FollowUp[] => {
  const today = getTodayIST();
  return [
    {
      followUpId: 'FU-2026-00041',
      patientId: 'RC-2026-004821',
      patientName: 'Suresh Patil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      date: today,
      time: '11:00 AM',
      mode: 'TELECONSULTATION',
      reason: 'Review breathing difficulty and response to bronchodilator',
      notes: 'Check SpO2 with pulse oximeter at home. Report if below 92%.',
      status: 'DUE',
      createdAt: `${today}T07:30:00.000Z`,
      updatedAt: `${today}T07:30:00.000Z`,
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00042',
      patientId: 'RC-2026-001042',
      patientName: 'Aarav Bhil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-RAJESH-02',
      doctorName: 'Dr. Rajesh Varma',
      date: today,
      time: '11:30 AM',
      mode: 'HW_VISIT',
      reason: 'Hydration assessment and ORS intake confirmation',
      notes: 'Inspect mucosal moisture, verify wet diaper count.',
      status: 'DUE',
      createdAt: `${today}T07:45:00.000Z`,
      updatedAt: `${today}T07:45:00.000Z`,
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00043',
      patientId: 'RC-2026-003290',
      patientName: 'Kavita Gawit',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-PRIYA-04',
      doctorName: 'Dr. Priya Patil',
      date: today,
      time: '02:30 PM',
      mode: 'TELECONSULTATION',
      reason: 'Hemoglobin test verification & IFA compliance',
      notes: 'Ensure taking IFA tabs after meals, verify diet.',
      status: 'DUE',
      createdAt: `${today}T08:00:00.000Z`,
      updatedAt: `${today}T08:00:00.000Z`,
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00044',
      patientId: 'RC-2026-002115',
      patientName: 'Namdeo Sonawane',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      date: today,
      time: '03:00 PM',
      mode: 'HW_VISIT',
      reason: 'Knee mobilization exercise compliance check',
      notes: 'Verify NSAID tolerance, check for gastric irritation.',
      status: 'DUE',
      createdAt: `${today}T08:15:00.000Z`,
      updatedAt: `${today}T08:15:00.000Z`,
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00045',
      patientId: 'RC-2026-005102',
      patientName: 'Shantabai Bhil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      date: today,
      time: '03:30 PM',
      mode: 'IN_PERSON',
      reason: 'Blood pressure re-check following dosage increase',
      notes: 'Target BP < 140/90 mmHg.',
      status: 'DUE',
      createdAt: `${today}T08:30:00.000Z`,
      updatedAt: `${today}T08:30:00.000Z`,
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00038',
      patientId: 'RC-2026-005180',
      patientName: 'Janardhan Mali',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      date: '2026-09-15',
      time: '10:00 AM',
      mode: 'IN_PERSON',
      reason: 'Suture removal post minor abscess drainage',
      notes: 'Patient did not arrive at PHC on 15 Sep. Needs rescheduling.',
      status: 'MISSED',
      createdAt: '2026-09-10T09:00:00.000Z',
      updatedAt: '2026-09-16T00:00:00.000Z',
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00039',
      patientId: 'RC-2026-005191',
      patientName: 'Ashok Thakare',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-MAHAJAN-03',
      doctorName: 'Dr. S. K. Mahajan',
      date: '2026-09-16',
      time: '11:00 AM',
      mode: 'TELECONSULTATION',
      reason: 'Post-TB treatment monthly follow-up & sputum review',
      notes: 'Missed scheduled call on 16 Sep. ASHA to visit home.',
      status: 'MISSED',
      createdAt: '2026-09-11T10:00:00.000Z',
      updatedAt: '2026-09-17T00:00:00.000Z',
      syncStatus: 'synced',
    },
    {
      followUpId: 'FU-2026-00050',
      patientId: 'RC-2026-004821',
      patientName: 'Suresh Patil',
      healthWorkerId: 'HW-SUNITA-001',
      doctorId: 'DOC-ANJALI-01',
      doctorName: 'Dr. Anjali Sharma',
      date: '2026-09-22',
      time: '10:30 AM',
      mode: 'IN_PERSON',
      reason: 'Spirometry and maintenance inhaler review',
      status: 'UPCOMING',
      createdAt: `${today}T09:00:00.000Z`,
      updatedAt: `${today}T09:00:00.000Z`,
      syncStatus: 'synced',
    },
  ];
};
